### ISSUE TITLE
Loading library in R gives an error

### ISSUE THREAD

**Issue by kmbuki** [paterijk/MCDA#12]
Running in R studio
Error in library(paterijk/MCDA) : 'package' must be of length 1

<img width="486" alt="screen shot 2017-12-28 at 23 07 32" src="https://user-images.githubusercontent.com/14215807/34425460-0a546718-ec24-11e7-8d63-e1f9ce081452.png">

Running the same on https://rdrr.io gives
<img width="1122" alt="screen shot 2017-12-28 at 23 07 21" src="https://user-images.githubusercontent.com/14215807/34425456-03c8fd64-ec24-11e7-9f75-2f9cbea2d711.png">

Error in library(paterijk/MCDA) : 'package' must be of length 1
Execution halted

**Comment by jonasW3F** [comment]
Did you just try to do library(MCDA)
